services:
  db:
    image: postgres:15
    container_name: ecommerce_db
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "5432:5432"
  
  app:
    image: ecommerce-image:1.2
    build: .
    container_name: ecommerce_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  db: {}
  pgadmin: {}
