services:
  server:
    build: ./server
    image: ecommerce_server
    container_name: ecommerce_server
    volumes:
      - ./server:/server
    working_dir: /server
    command: ./runserver.sh
    ports:
      - "8000:8000"

  client:
    image: node:latest
    container_name: ecommerce_client
    volumes:
      - ./client:/client
    working_dir: /client
    command: ./runclient.sh
    ports:
      - "5173:5173"
    depends_on:
      - server
