services:
  nginx:
    image: ecommerce_nginx:1.0.0
    build: ./nginx
    container_name: ecommerce_nginx
    restart: unless-stopped
    volumes:
      - static_files:/app/static/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logrotate_nginx.conf:/etc/logrotate.d/nginx
      - ./nginx/log/:/var/log/nginx/
    ports:
      - "80:80"
    depends_on:
      - app
  
  app:
    image: ecommerce-image:1.0.4
    build: ./ecommerce
    container_name: ecommerce_app
    env_file:
      - ecommerce/.env
    working_dir: /app
    command: ./entrypoint.sh
    volumes:
      - ./ecommerce/:/app
      - static_files:/app/static
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: ecommerce_db
    env_file:
      - ecommerce/.env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce_pgadmin
    env_file:
      - ecommerce/.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8002:80"
    restart: unless-stopped

volumes:
  static_files: {}
  db: {}
  pgadmin: {}
